version: '3'

services:
  app:
    build: docker/go
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/edm20627/xxx
    ports:
      - 8080:8080
      - 8000:8000
    restart: 'no'
    command: make serve