serve:
	dev_appserver.py app.yaml --host=0.0.0.0 --admin_host=0.0.0.0 --support_datastore_emulator=False
	# dev_appserver.py app.yaml --host=0.0.0.0 --admin_host=0.0.0.0  --datastore_path .datastore
	# dev_appserver.py app.yaml --host=0.0.0.0 --admin_host=0.0.0.0
